name: Bug report
description: Report a reproducible problem in yante
title: "[Bug]: "
labels:
  - bug
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        thanks for taking the time to file a bug! please fill out the form below so I can reproduce and fix the issue.

  - type: input
    id: summary
    attributes:
      label: short summary
      placeholder: "timer pauses when switching tabs"

  - type: textarea
    id: steps
    attributes:
      label: steps to reproduce
      description: Provide exact, minimal steps. Include links/files if relevant.
      placeholder: |
        1. Open new tab with yante
        2. Start Pomodoro
        3. Switch to another tab
        4. Return to yante tab
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: expected behavior
      placeholder: "Pomodoro continues running in the background."

  - type: textarea
    id: actual
    attributes:
      label: actual behavior
      placeholder: "Timer is paused or reset after switching tabs."

  - type: dropdown
    id: severity
    attributes:
      label: severity
      options:
        - Critical - data loss/crash
        - High - broken core application
        - Medium - workaround exists
        - Low - minor issue
        - Cosmetic
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: yante version
      placeholder: "e.g., 0.1.0"

  - type: dropdown
    id: browsers
    attributes:
      label: browser name
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Arc
        - Brave
        - Other

  - type: input
    id: browser_version
    attributes:
      label: browser version
      placeholder: "e.g., 128.0.0"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / screen recording
      description: Drag & drop files here to attach.

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: i have searched existing issues and discussions & could not find a similar one
          required: true
        - label: i can consistently reproduce this issue
