name: Bug report
description: Report a reproducible problem in Yante
title: "[Bug]: "
labels:
  - bug
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug! Please fill out the form below so we can reproduce and fix the issue quickly.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: One-sentence description of the problem.
      placeholder: "Timer pauses when switching tabs"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact, minimal steps. Include links/files if relevant.
      placeholder: |
        1. Open new tab with Yante
        2. Start Pomodoro
        3. Switch to another tab
        4. Return to Yante tab
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Pomodoro continues running in the background."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Timer is paused or reset after switching tabs."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical - data loss/crash
        - High - broken core workflow
        - Medium - workaround exists
        - Low - minor issue
        - Cosmetic
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Affected area(s)
      multiple: true
      options:
        - Pomodoro
        - Clock
        - Canvas/Widgets
        - Settings
        - Drag & Drop
        - UI/Styling
        - Storage/Sync
        - Build/Release
        - Other
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Yante version
      placeholder: "e.g., 0.1.0 (from extension details)"
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s)
      multiple: true
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Arc
        - Brave
        - Other
    validations:
      required: true

  - type: input
    id: browser_version
    attributes:
      label: Browser version
      placeholder: "e.g., 128.0.0"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS version
      placeholder: "e.g., macOS 14.6"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Console logs / errors
      description: Open DevTools (Console) and paste relevant messages.
      render: shell
      placeholder: |
        Uncaught TypeError: ...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / screen recording
      description: Drag & drop files here to attach.
    validations:
      required: false

  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      options:
        - label: This worked in a previous version of Yante
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: I can consistently reproduce this issue
          required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: Links, configs, specific settings, etc.
    validations:
      required: false
