name: Feature request
description: Suggest a new capability or improvement for Yante
title: "[Feature]: "
labels:
  - feature
  - enhancement
  - needs-triage
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement! Clear, focused requests help us evaluate and implement faster.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: One-sentence description of the feature.
      placeholder: "Add long-break duration customization"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem or limitation does this address?
      placeholder: "Default 10-minute long break doesn't fit my routine."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature, behavior, or API. Include configuration, UI, or interactions.
      placeholder: "Allow setting long-break duration between 5–30 minutes in Settings > Pomodoro."
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale / Benefits
      description: Why is this valuable? Who benefits?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Pomodoro
        - Clock
        - Bookmarks
        - Timer
        - Stopwatch
        - Wallpaper
        - Quotes
        - Music
        - Tasks
        - Calendar
        - Emails
        - News
        - Reminders
        - Settings
        - Canvas/Widgets
        - Other
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of verifiable outcomes.
      placeholder: |
        - User can set long-break duration between 5–30 minutes
        - Setting persists between sessions
        - Timer reflects updated duration
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Use external timer app; keep default duration"
    validations:
      required: false

  - type: textarea
    id: design
    attributes:
      label: UX / Design notes
      description: Wireframes, mockups, or interaction details.
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / related issues
      placeholder: "Blocked by #123; relates to #456"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - must have
        - P1 - high
        - P2 - medium
        - P3 - low
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: I checked the roadmap to avoid duplicates
          required: true
        - label: I’m willing to contribute a PR
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Links, examples, related products, constraints.
    validations:
      required: false
